PROBLEM 1


INTRODUCTION


Say "Hello, World!" With Python

In [2]:
print("Hello, World!")

Hello, World!


Python If-Else

In [1]:
import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input().strip())
    if n%2!=0: 
        print("Weird")
    elif 2<=n<=5: 
        print("Not Weird")
    elif 6<=n<=20:
        print("Weird")
    elif n>20:
        print("Not Weird")

10
Weird


Arithmetic Operators

In [6]:
if __name__ == '__main__':
    a = int(input())
    b = int(input())


print(a+b)
print(a-b)
print(a*b)


24
25
49
-1
600


Python: Division

In [ ]:
if __name__ == '__main__':    
    a = int(input())
    b = int(input())
print(a//b)
print(a/b)


Loops

In [ ]:
if __name__ == '__main__':
    n = int(input())
    for i in range(0,n):
        print(i**2)

   Write Function

In [4]:
def is_leap(year):
    leap = False
    if year % 4 == 0 and  year % 100 != 0 or year %400==0: 
        leap=True
    else:
        leap=False

    # Write your logic here
    
    return leap

year = int(input())
print(is_leap(year))

2010
False


Print Function

In [14]:
if __name__ == '__main__':
  n = int(input())

for i in range(1,n+1):
    print(i,end='')

4
1234

BASIC DATA TYPES

List Comprehensions

In [15]:
if __name__ == '__main__':
    x = int(input())
    y = int(input())
    z = int(input())
    n = int(input())
array = [] 
    

for i in range(x+1):
    for j in range(y+1): 
        for k in range(z+1):
            if i + j + k !=n: 
                array.append([i,j,k])
print(array)

2
3
4
5
[[0, 0, 0], [0, 0, 1], [0, 0, 2], [0, 0, 3], [0, 0, 4], [0, 1, 0], [0, 1, 1], [0, 1, 2], [0, 1, 3], [0, 2, 0], [0, 2, 1], [0, 2, 2], [0, 2, 4], [0, 3, 0], [0, 3, 1], [0, 3, 3], [0, 3, 4], [1, 0, 0], [1, 0, 1], [1, 0, 2], [1, 0, 3], [1, 1, 0], [1, 1, 1], [1, 1, 2], [1, 1, 4], [1, 2, 0], [1, 2, 1], [1, 2, 3], [1, 2, 4], [1, 3, 0], [1, 3, 2], [1, 3, 3], [1, 3, 4], [2, 0, 0], [2, 0, 1], [2, 0, 2], [2, 0, 4], [2, 1, 0], [2, 1, 1], [2, 1, 3], [2, 1, 4], [2, 2, 0], [2, 2, 2], [2, 2, 3], [2, 2, 4], [2, 3, 1], [2, 3, 2], [2, 3, 3], [2, 3, 4]]


Find the Runner-Up Score!

In [ ]:
n = int(input())
arr = sorted(list(map(int, input().split())))
max = -100
runner = -100
for i in arr:
    if i > max:
        runner = max
        max = i
print(runner)

Nested Lists

In [43]:
score_student= [] 
score_list = []
for _ in range(int(input())):
    name = input()
    score = float(input())
    score_student.append([name,score])
    score_list.append(score)


second_lowest_score = sorted(list(dict.fromkeys(score_list)))[1]

for name,marks in sorted(score_student):
    if marks == second_lowest_score:
        print(name)

Finding the percentage

In [ ]:
from decimal import Decimal
from statistics import mean 

if __name__ == '__main__':
    n = int(input())
    student_marks = {}
    for _ in range(n):
        name, *line = input().split()
        scores = list(map(float, line))
        student_marks[name] = scores
    query_name = input()
print(round(Decimal(mean(student_marks[query_name])),2)) 





Lists

In [ ]:
array = []
n = int(input())
for i in range(0, n):
    object = input().split()

    if object[0] == 'insert':
        array.insert(int(object[1]), int(object[2]))
    elif object[0] == 'print':
        print (array)
    elif object[0] == 'remove':
         array.remove(int(object[1]))
    elif object[0] == 'append':
         array.append(int(object[1]))
    elif object[0] == 'sort':
         array.sort()
    elif object[0] == 'pop':
         array.pop()
    elif object[0] == 'reverse':
         array.reverse()

Tuples

In [59]:
if __name__ == '__main__':
    n = int(input())
    integer_list = map(int, input().split())
    print(hash(tuple(integer_list)), end="")


2
1 2 
2


STRINGS

sWAP cASE

In [ ]:
def swap_case(s):
    new = ''                  #creo la stringa nuova vuota dove inserirò i caratteri modificati
    for c in s:                 #per ogni carattere nella string di input, controllo
        if c.islower():         #se il carattere è minuscolo
            new += c.upper()    #lo scrivo maiuscolo nella stringa nuova
        else:                   #se è maiuscolo
            new += c.lower()    #lo scrivo minuscolo
    return new                  #ritorno la stringa nuova che ora contiene i caratteri scambiati


if __name__ == '__main__':
    s = input()
    result = swap_case(s)
    print(result)

String Split and Join

In [66]:
def split_and_join(line):
    line=line.split(" ")
    line="-".join(line)
    return line
if __name__ == '__main__':
    line = input()
    result = split_and_join(line)
    print(result)

ciao none
ciao-none


What's Your Name?


In [73]:
def print_full_name(a, b):
    print("Hello "+a+' '+b+"!"+" You just delved into python.",end="")
    
if __name__ == '__main__':
    first_name = input()
    last_name = input()
    print_full_name(first_name, last_name)

Mutations

In [ ]:
def mutate_string(s, i, c):
   s=s[:i]+c+s[i+1:]
   return s
if __name__ == '__main__':
    s = input()
    i, c = input().split()
    s_new = mutate_string(s, int(i), c)
    print(s_new)

Find a string

In [ ]:
def count_substring(string, sub_string):
    count=0  
    idx=None    
    for i in range(len(string)):
        if len(string)>len(sub_string):             
            idx=string.find(sub_string)            
            if (idx>=0):
                count += 1
            string=string[(idx+1):]
    return count
if __name__ == '__main__':
    string = input().strip()
    sub_string = input().strip()
    
    count = count_substring(string, sub_string)
    print(count)

String Validators

In [ ]:
s=input()
print(any(map(str.isalnum,s)))
print(any(map(str.isalpha,s)))
print(any(map(str.isdigit,s)))
print(any(map(str.islower,s)))
print(any(map(str.isupper,s)))

Text Alignment

In [ ]:
#Replace all ____ with rjust, ljust or center. 

thickness = int(input()) #This must be an odd number
c = 'H'

#Top Cone
for i in range(thickness):
    print((c*i).rjust(thickness-1)+c+(c*i).ljust(thickness-1))

#Top Pillars
for i in range(thickness+1):
    print((c*thickness).center(thickness*2)+(c*thickness).center(thickness*6))

#Middle Belt
for i in range((thickness+1)//2):
    print((c*thickness*5).center(thickness*6))    

#Bottom Pillars
for i in range(thickness+1):
    print((c*thickness).center(thickness*2)+(c*thickness).center(thickness*6))    

#Bottom Cone
for i in range(thickness):
    print(((c*(thickness-i-1)).rjust(thickness)+c+(c*(thickness-i-1)).ljust(thickness)).rjust(thickness*6))

Text Wrap

In [ ]:
import textwrap

def wrap(string, max_width):
    for i in range(0,len(string)+1,max_width):
        print(string[i:max_width+i])
if __name__ == '__main__':
    string, max_width = input(), int(input())
    result = wrap(string, max_width)
    print(result)

Designer Door Mat

In [ ]:
N,M=map(int,input().split())
a=[('.|.'*i).center(M,'-') for i in range(1,N,2)]
for b in a+['WELCOME'.center(M,'-')]+list(reversed(a)):
                print(b)

String Formatting

In [ ]:
def print_formatted(number):
    width = len('{:b}'.format(number))
    for i in range(1, number+1):
         print (str.rjust(str(i), width),\
        str.rjust('{:o}'.format(i), width),\
        str.rjust('{:X}'.format(i), width),\
        str.rjust('{:b}'.format(i), width))
    
if __name__ == '__main__':
    n = int(input())
    print_formatted(n)

Alphabet Rangoli

In [ ]:
def print_rangoli(size):
    alphabet = "abcdefghijklmnopqrstuvwxyz"
    sub_alph = alphabet[:size]
    width = 4*size - 3
     
    for i in range(size):
         print((("-".join(sub_alph[-1-i:])[1:])[::-1] +  "-".join(sub_alph[-1-i:])).center(width,"-"))
 
    for i in reversed(range(size-1)):
        print((("-".join(sub_alph[-1-i:])[1:])[::-1] +  "-".join(sub_alph[-1-i:])).center(width,"-"))
         

if __name__ == '__main__':
    n = int(input())
    print_rangoli(n)

Capitalize!

In [ ]:
def solve(s):
    names = s.split(' ')
    S= []
    a=' '
    for name in names:
        S.append(name.capitalize ())
    result= a.join(S)
    return(result)
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = solve(s)

    fptr.write(result + '\n')

    fptr.close()

The minion game

In [ ]:
def minion_game(s):
    V = frozenset("AEIOU")
    n = len(s)
    ksc = sum(q for c, q in zip(s, range(n, 0, -1)) if c in V)
    ssc = n * (n + 1) // 2 - ksc
    if ksc > ssc:
        print("Kevin {:d}".format(ksc))
    elif ssc > ksc:
        print("Stuart {:d}".format(ssc))
    else:
        print("Draw")
if __name__ == '__main__':
    s = input()
    minion_game(s)

Merge the Tools!

In [ ]:
import textwrap
from collections import OrderedDict
 
def merge_the_tools(string, k):
     
    #split string into k slices
    list_t = textwrap.wrap(string, k)
    #use orderedDict to remove duplicates preserving 
    for t in list_t:
        print("".join(OrderedDict.fromkeys(t)))
if __name__ == '__main__':
    string, k = input(), int(input())
    merge_the_tools(string, k)

SETS
Introduction to Sets

In [ ]:
def average(array):
    # your code goes here
    return sum(set(array))/len(set(array))
if __name__ == '__main__':
    n = int(input())
    arr = list(map(int, input().split()))
    result = average(arr)
    print(result)

No Idea!

In [ ]:
count = list(map(int,input().strip().split()))
m = count[0]
n = count[1]
Arr = list(map(int,input().strip().split()))
A = set(map(int,input().strip().split()))
B = set(map(int,input().strip().split()))
happy = 0
for i in Arr:
    if i in A : happy = happy + 1
    elif i in B : happy = happy - 1
print (happy  ) 

Symmetric Difference

In [ ]:
M = input()
a = input()
lst1 = a.split()
newlst1 = list(map(int, lst1))
set1 = set(newlst1)
N = input()
b = input()
lst2 = b.split()
newlst2 = list(map(int, lst2))
set2 = set(newlst2)
x = set1.difference(set2)
#print x
y = set2.difference(set1)
#print y
z = set()
z = x.union(y)
#print z
lst = list(z)
lst = sorted(lst)
for i in range(len(lst)):
    print (lst[i])

Set.add()

In [ ]:
settino = set()
n = int(input())

for _ in range(n):
    settino.add(input())

print (len(settino))

Set .discard(), .remove() & .pop()

In [ ]:
n = int(input())
s = set(map(int, input().split()))
m=int(input())
for i in range(m):
    p= input().split()
    if p[0]=="remove":
        s.remove(int(p[1]))
    elif p[0]=="discard":
        s.discard(int(p[1]))
    else:
        s.pop()
print (sum(list(s)))

Set .union() Operation

In [ ]:
n1=input()
s1=set(input().split(" "))
n2=input()
s2=set(input().split(" "))
s3=s1.union(s2)
print (len(s3))

Set .intersection() Operation



In [ ]:
input()
A = set(input().split(" "))

input()
B = set(input().split(" "))

print (len(A.intersection(B)))

Set .difference() Operation

In [ ]:
eng=int(input())
rn1=list(map(int,input().split()))
fre=int(input())
rn2=list(map(int,input().split()))
count=0
for i in rn1:
    if i not in rn2:
        count=count+1
print(count)

Set .symmetric_difference() Operation

In [ ]:
a=int(input())
a1=input()
b=int(input())
b1=input()
k1=a1.split(" ")
k2=b1.split(" ")
k1n= list(map(int, k1))
k2n= list(map(int, k2))
ms1=set(k1n)
ms2=set(k2n)
l=ms1.symmetric_difference(ms2)
print(len(l))

Set Mutations



In [ ]:
if __name__ == '__main__':
    (_, A) = (int(input()),set(map(int, input().split())))
    B = int(input())
    for _ in range(B):
        (command, newSet) = (input().split()[0],set(map(int, input().split())))
        getattr(A, command)(newSet)

    print (sum(A))

The Captain's Room

In [ ]:
k = int(input())
L = str(input()).split(" ")
family = L
total = set(L)
for r in set(L):
    try:
        family.remove(r)
    except:
        pass
print ("".join((total - set(family))))

Check Subset

In [ ]:
import sys
#This is a kind of golf mission; submit only below.
for _ in range(int(input())):
    input();s1=set(map(int,input().split()))
    input();s2=set(map(int,input().split()))
    print(s2==s1.union(s2))

Check Strict Superset

In [ ]:
A = set(map(int,input().split()))
b = False
for _ in range(int(input())):
    s = set(map(int, input().split()))
    if A.issuperset(s):
        if len(A)>len(s):
            b = True
        else:
            b = False
            break
    else:
        b = False
        break
print(b)

COLLECTIONS

collections.Counter()

In [ ]:
from collections import Counter
X = int(input())
sizes = Counter(map(int, input().split()))
N = int(input())

money = 0

for i in range(N):
    (size, price) = map(int, input().split())

    if sizes[size] > 0:
        sizes[size] -= 1
        money += price

print(money)

DefaultDict Tutorial



In [ ]:
from collections import defaultdict
N,M=map(int,input().split())
d=defaultdict(list)
for i in range(N):
    s=input().rstrip()
    d[s].append(i+1)
for _ in range(M):
    s=input().rstrip()
    if s in d:
        print(' '.join(map(str,d[s])))
    else:
        print('-1')

Collections.namedtuple()



In [9]:
from __future__ import division
import collections

N = int(input())
columns = ','.join(input().split())
Student = collections.namedtuple('Student', columns)

sum = 0
for i in range(N):
    line = input().split()
    student = Student(*line)
    sum += int(student.MARKS)

print (sum / N)

3


Collections.OrderedDict()



In [ ]:
from collections import OrderedDict

number_ = int(input())
odict = OrderedDict()
for i in range(number_):
    litem = input().split(' ')
    price = int(litem[-1])
    item_name = " ".join(litem[:-1])
    if odict.get(item_name):
        odict[item_name] += price
    else:
        odict[item_name] = price

for i,v in odict.items():
    print(i,v)

Word Order 

In [ ]:
from collections import Counter
from collections import OrderedDict

n = int(input())    #numero di linee che avrò in input
ordered_dict = OrderedDict()
for i in range(n):
    a = str(input())
    if a in ordered_dict.keys():
        ordered_dict[a] += 1
    else:
        ordered_dict[a] = 1
print(len(ordered_dict))
s = ""
for i in ordered_dict.values():
    s += str(i)+" "
print(s)

Collections.deque()

In [ ]:
from collections import deque

d = deque()

for _ in range(int(input())):
    args = input().strip().split()
    if (args[0] == 'append'):
        d.append(args[1])
    elif (args[0] == 'pop'):
        d.pop()
    elif (args[0] == 'popleft'):
        d.popleft()
    elif (args[0] == 'appendleft'):
        d.appendleft(args[1])

print (' '.join(d))

Company Logo

In [ ]:
commons = dict()
counter = dict()

def key(item):
    return item[1]*128 + 128-ord(item[0])

for c in input():
    counter[c] = counter.get(c, 0) + 1

for k, v in counter.items():
    if len(commons) < 3:
        commons[k] = v
    else:
        min_item = min(commons.items(), key=key)
        commons.pop(min_item[0])
        max_item = max(min_item, (k, v), key=key)
        commons[max_item[0]] = max_item[1]

for item in sorted(commons.items(), key=key, reverse=True):
    print("%s %d" % item)

Piling Up!


In [ ]:
from collections import deque
for _ in range(int(input())):
    flag = True
    input()
    d = deque(map(int, input().strip().split()))
    if (d[0] >= d[-1]):
        max = d.popleft()
    else:
        max = d.pop()
    while d:
        if (len(d) == 1):
            if (d[0] <= max):
                break
            else:
                flag = False
                break;
        else:
            if d[0] <= max and d[-1] <= max:
                if d[0] >= d[-1]:
                    max = d.popleft()
                else:
                    max = d.pop()
            elif d[0] <= max:
                max = d.popleft()
            elif d[-1] <= max:
                max = d.pop()
            else:
                flag = False
                break;

    if flag:
        print ("Yes")
    else:
        print ("No")

DATE AND TIME 

Calendar Module 

In [11]:
import calendar

date = input().strip().split()

days = list(calendar.day_name)
print (days[calendar.weekday(int(date[2]), int(date[0]), int(date[1]))].upper() )

<class 'calendar.TextCalendar'>


Time Delta



In [ ]:
###

Exceptions


In [13]:
for i in range(int(input())):  
    try:
        a,b= map(int,input().split())
        print(a//b)
    except BaseException as e:
        print("Error Code:",e)

3
1 3
0
2 5 
0
444
Error Code: not enough values to unpack (expected 2, got 1)


Built-ins

Zipped

In [ ]:
n, x = input().split()
n = int(n)  # student count
x = int(x)  # subject count
grades = [list(map(float, input().split())) for i in range(x)]
grades_by_student = zip(*grades)
average_by_student = [sum(i) / len(i) for i in list(grades_by_student)]
average_by_student = [round(i, 1) for i in average_by_student]

for i in average_by_student:
    print(i)



Athlete Sort



In [ ]:
###

ginortS

In [46]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

s=input()
lista_m=[]
lista_min=[]
lista_p=[]
lista_d=[]
for i in range(0,len(s)):
    if s[i].isalpha():
        if s[i].isupper()==True:
            lista_m.append(s[i])
        else:
            lista_min.append(s[i])
    elif s[i].isnumeric():
        if int(s[i])%2==0:
            lista_p.append(s[i])
        else:
            lista_d.append(s[i])
            
lista_m.sort()
lista_min.sort()
lista_p.sort()
lista_d.sort()


lista=lista_min+lista_m+lista_d+lista_p
print("".join(lista))




Sorting1234
ginortS1324


Map and Lambda Function

In [ ]:
cube = lambda x: x ** 3


def fibonacci(n):
    a, b, c = 0, 1, 1
    for _ in range(n):
        yield a
        a, b = b, a + b


if __name__ == '__main__':
    n = int(input())
    print(list(map(cube, fibonacci(n))))

REGEX AND PARSING /17

Detect Floating Point Number

In [ ]:
#import re

#n=input()
#if n.isnumeric()==False:
 #   print(False)
#else:
#    if n[0]=='+':
 #       print(bool(re.match(r"+",n)))
  #  if n[0]=='-':
   #     print(bool(re.match(r"-",n)))
    
    
#print (bool(re.match(r"ly","similarly")))
#print (bool(re.match(r"ly","ly should be in the beginning")))
import re
for i in range(int(input())):
    print(bool(re.search(r"^[+-]?\d*\.\d+$",input().strip())))



Re.split()


In [ ]:
import re
regex_pattern = r"[.,]"    # Do not delete 'r'.
print("\n".join(re.split(regex_pattern, input())))

Group(), Groups() & Groupdict()


In [3]:
#solution found online
import re
#m = re.match(r'(\w+)@(\w+)\.(\w+)','username@hackerrank.com')
#m.group(0)       # The entire match 
#'username@hackerrank.com'
#m.group(1)       # The first parenthesized subgroup.
#'username'
#m.group(2)       # The second parenthesized subgroup.
#'hackerrank'
#m.group(3)       # The third parenthesized subgroup.
#'com'
#m.group(1,2,3)   # Multiple arguments give us a tuple.
#('username', 'hackerrank', 'com')

#m = re.match(r'(?P<user>\w+)@(?P<website>\w+)\.(?P<extension>\w+)','myname@hackerrank.com')
#m.groupdict()
#{'website': 'hackerrank', 'user': 'myname', 'extension': 'com'}

m = re.search(r'([a-zA-Z0-9])\1+', input().strip())
print(m.group(1) if m else -1)

45554
5


Re.findall() & Re.finditer()

In [ ]:
#found online 
import re
vowels = 'aeiou'
consonants = 'qwrtypsdfghjklzxcvbnm'
match = re.findall(r'(?<=[' + consonants + '])([' + vowels + ']{2,})(?=[' + consonants + '])', input(), flags=re.I)
print('\n'.join(match or ['-1']))

Re.start() & Re.end()



In [4]:
import re
string = input()
substring = input()
pattern = re.compile(substring)
match = pattern.search(string)
if not match: print('(-1, -1)')
while match:
    print('({0}, {1})'.format(match.start(), match.end() - 1))
    match = pattern.search(string, match.start() + 1)

ciaos
fer
(-1, -1)


Regex Substitution

In [ ]:
import re
for _ in range(int(input())):
    print(re.sub(r'(?<= )(&&|\|\|)(?= )', lambda x: 'and' if x.group() == '&&' else 'or', input()))

453
234
234


243
243
43
43
2
2




stop
stop
brek34
brek34
cfg56
cfg56
53
53


cgf34
cgf34
32
32
12
12
43255
43255




0
0
break
break
adspjoj41ì049ì1ù
adspjoj41ì049ì1ù




Validating Roman Numeral

In [1]:
import re
pattern = '^(?=[MDCLXVI])M{0,3}(CM|CD|D?C{0,3})(XC|XL|L?X{0,3})(IX|IV|V?I{0,3})$'
roman = str(input())
if re.search(pattern, roman):
    print ('True')
else:
    print ('False')

CV
True


Validating phone numbers



In [ ]:
import re

N = int(input())
r = re.compile("^[789]\d{9}$")

for _ in range(N):
    t = input()
    print("YES" if r.search(t) else "NO")

Validating and Parsing Email Addresses



In [ ]:
import re

n=int(input())
for i in range(n):
    line= input()
    name,email=line.split(' ')
    pattern="<[a-z][a-zA-Z0-9\-\.\_]+@[a-zA-Z]+\.[a-zA-Z]{1,3}>"
    if bool(re.match(pattern,email)):
        print (name,email)

Hex Color Code



In [ ]:
import re

for _ in range(int(input())):
    matches = re.findall(r':?.(#[0-9a-fA-F]{6}|#[0-9a-fA-F]{3})', input())
    if matches:
        print(*matches, sep='\n')

HTML Parser - Part 1



In [ ]:
import re

tag_filter = re.compile(r"(?<=<)(?:.*?)(?=>)")
attrib_filter = re.compile(r"([\w-]+)(?:=[\"'](.*?)[\"'])?")

s = ""

# get input stream
for _ in range(int(input())):
    s += input()

# discard comments
s = re.sub(r"(?:<!--(.|\s)*?(?:-->))","",s)

# extract individual tag information
tags = tag_filter.findall(s)

# iterate over the extracted tag information
for tag in tags:
    # tag handling logic
    if tag[0] == "/":
        print("End   :",tag[1:])
    else:
        attribs = attrib_filter.findall(tag)
        if tag[-1] == "/":
            print("Empty :",attribs[0][0])
        else:
            print("Start :",attribs[0][0])
            
        for i in range(1,len(attribs)):
            a = attribs[i][0]
            if attribs[i][1] == '': 
                v = 'None' 
            else: 
                v = attribs[i][1]
            print("-> {} > {}".format(a,v))

HTML Parser - Part 2



In [2]:
###

Detect HTML Tags, Attributes and Attribute Values



In [ ]:
import re

text = ''
for _ in range(int(input())):
    text = re.sub(r'<!.+-->',r' ',(text+input()))

for er in re.findall(r'<([^/][^>]*)>', text):
    if ' ' in er:       
        for ere in re.findall(r'([a-z]+)? *([a-z-]+)="([^"]+)', er):
            if ere[0]:
                print(ere[0])          
            print('-> '+ere[1]+' > '+ere[2])
    else:
        print(er)

Validating UID



In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

import re

for _ in range(int(input())):
    u = ''.join(sorted(input()))
    try:
        assert re.search(r'[A-Z]{2}', u)
        assert re.search(r'\d\d\d', u)
        assert not re.search(r'[^a-zA-Z0-9]', u)
        assert not re.search(r'(.)\1', u)
        assert len(u) == 10
    except:
        print('Invalid')
    else:
        print('Valid')

Validating Credit Card Numbers

In [ ]:
import re
n=int(input())
for i in range(n):
    string = input()
    start = re.search(r"^[456]",string)
    digit_and_sep = re.match(r"(-?\d{4}){4}$",string)
    consecutive = re.search(r"(.)(-?\1){3,}",string)
    if ( start and digit_and_sep  and not consecutive):
        print("Valid")
    else:
        print("Invalid") 

Validating Postal Codes



In [ ]:
regex_integer_in_range = r'^[1-9][\d]{5}$'  # Do not delete 'r'.
regex_alternating_repetitive_digit_pair = r'(\d)(?=\d\1)'  # Do not delete 'r'.


import re
P = input()

print (bool(re.match(regex_integer_in_range, P)) 
and len(re.findall(regex_alternating_repetitive_digit_pair, P)) < 2)

Matrix Script



In [5]:
import re

n, m = map(int, input().split())
a, b = [], ''
for _ in range(n):
    a.append(input())

for z in zip(*a):
    b += ''.join(z)

print(re.sub(r'(?<=\w)([^\w]+)(?=\w)', ' ', b))
for _ in range(n):
    matrix_item = input()
    matrix.append(matrix_item)

7 3 Tsi h%x i # sM  $a  #t% ir!


ValueError: invalid literal for int() with base 10: 'Tsi'

XML

XML 1 - Find the Score



In [ ]:
import sys
import xml.etree.ElementTree as etree

def get_attr_number(node):
    return len(node.attrib) + sum(get_attr_number(child) for child in node);

if __name__ == '__main__':
    sys.stdin.readline()
    xml = sys.stdin.read()
    tree = etree.ElementTree(etree.fromstring(xml))
    root = tree.getroot()
    print(get_attr_number(root))

XML2 - Find the Maximum Depth

In [ ]:
import xml.etree.ElementTree as etree

maxdepth = 0


def depth(elem, level):
    global maxdepth
    if (level == maxdepth):
        maxdepth += 1

    for child in elem:
        depth(child, level + 1)
if __name__ == '__main__':
    n = int(input())
    xml = ""
    for i in range(n):
        xml =  xml + input() + "\n"
    tree = etree.ElementTree(etree.fromstring(xml))
    depth(tree.getroot(), -1)
    print(maxdepth)

CLOSURES AND DECORATORS

Standardize Mobile Number Using Decorators



In [ ]:
def wrapper(f):
    def fun(l):
        f(['+91 ' + c[-10:-5] + ' ' + c[-5:] for c in l])

    return fun
@wrapper
def sort_phone(l):
    print(*sorted(l), sep='\n')

if __name__ == '__main__':
    l = [input() for _ in range(int(input()))]
    sort_phone(l) 


Decorators 2 - Name Directory



In [ ]:
import operator

def person_lister(f):
    def inner(people):
        return map(f, sorted(people, key=lambda x: x[2]))
    return inner

@person_lister
def name_format(person):
    return ("Mr. " if person[3] == "M" else "Ms. ") + person[0] + " " + person[1]

if __name__ == '__main__':
    people = [input().split() for i in range(int(input()))]
    print(*name_format(people), sep='\n')

NUMPY

Arrays

In [8]:
import numpy
def arrays(arr):
    return (numpy.array(arr[::-1], float))
#micka simon nicolà
arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 14 6 
[ 6. 14.  1.]


Shape and Reshape

In [12]:
import numpy as np

print(np.array(input().split(), int).reshape(3, 3))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Transpose and Flatten



In [ ]:
import numpy as np

n, m = map(int, input().split())
array = np.array([input().strip().split() for _ in range(n)], int)
print(array.transpose())
print(array.flatten())

Concatenate

In [ ]:
import numpy as np

a, b, c = map(int, input().split())
A = np.array([input().split() for _ in range(a)], int)
B = np.array([input().split() for _ in range(b)], int)
print(np.concatenate((A, B), axis=0))

Zeros and Ones



In [18]:
import numpy

row,colums,times=map(int,input().split())
for i in range(times):
    print(numpy.zeros((row,colums), dtype = numpy.int))
    
for j in range(times):  
    print(numpy.ones((row,colums), dtype = numpy.int))

3 3 3 
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


Eye and Identity

In [25]:
import numpy

numpy.set_printoptions(sign=' ')
print(numpy.eye(*map(int, input().split())))

3 4
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]]


Array Mathematics



In [35]:
import numpy as np

n, m = map(int, input().split())
a, b = (np.array([input().split() for _ in range(n)], dtype=int) for _ in range(2))
print(a + b, a - b, a * b, a // b, a % b, a ** b, sep='\n')

Floor, Ceil and Rint



In [36]:
import numpy

numpy.set_printoptions(sign=' ')

a = numpy.array(input().split(),float)

print(numpy.floor(a))
print(numpy.ceil(a))
print(numpy.rint(a))

4
[ 4.]
[ 4.]
[ 4.]


Sum and Prod



In [ ]:
import numpy as np
x=list(map(int,input().split()))
l=[]
for a in range(x[0]):
    l.append(list(map(int,input().split())))
arr=np.array(l)
arr1=np.sum(l,axis=0)
print(np.prod(arr1))

Min and Max



In [ ]:
import numpy
arr=[]
n,m=map(int,input().split())
for row in range(n):
    my_arr=list(map(int,input().split()))
    arr.append(my_arr)
my_array=numpy.array(arr)
result=numpy.min(my_array, axis = 1)
print(max(result))

Mean, Var, and Std



In [ ]:
import numpy as np 

n,m = map(int, input().split())
b = []
for i in range(n):
    a = list(map(int, input().split()))
    b.append(a)

b = np.array(b)

np.set_printoptions(legacy='1.13')
print(np.mean(b, axis = 1))
print(np.var(b, axis = 0))
print(np.std(b))

Dot and Cross



In [ ]:
import numpy
n = int(input())

A = list()
for x in range(n):
    A.append(list(map(int,input().split())))

B = list()
for x in range(n):
    B.append(list(map(int,input().split())))

print (numpy.dot(A,B))

Inner and Outer



In [ ]:
import numpy as np

A = np.array(input().split(), int)
B = np.array(input().split(), int)
print(np.inner(A, B), np.outer(A, B), sep='\n')

Polynomials



In [ ]:
import numpy 
n = list(map(float,input().split()))
m = input()
print(numpy.polyval(n,int(m)))

Linear Algebra



In [ ]:
import numpy
N=int(input())
a=[]
for i in range(1,N+1):
    a.append(list(map(float,input().split())))
print (numpy.linalg.det(a))

PROBLEM 2 

Birthday Cake Candles

In [ ]:
from collections import Counter

def birthdayCakeCandles(n, ar):
    d = Counter(ar)
    largest_key = max(Counter.keys(d))
    return d.get(largest_key)
    # Complete this function

n = int(input().strip())
ar = list(map(int, input().strip().split(' ')))
result = birthdayCakeCandles(n, ar)
print(result)

Viral Advertising

In [39]:
m = [2]
for i in range(int(input())-1):
    m.append(int(3*m[i]/2))
print(sum(m))

4
15


Kangaroo

In [ ]:
x1, v1, x2, v2 = map(int, input().split())

# Note: 0 <= x1 < x2 <= 10000
# x1 + k.v1 = x2 + k.v2


if (v2 < v1) and ((x2 - x1) % (v2 - v1)) == 0:
    print("YES")
else:
    print("NO")

Insertion Sort 1

In [ ]:
def last_insertion_sort(sorted_array, value):
    item = a[-1]
    i = n - 1
    while (item >= value) and (i > 0):
        i -= 1
        item = a[i]
        if item < value:
            a[i + 1] = value
        else:
            a[i + 1] = a[i]
        print(*a, sep=" ")
    if item >= value:
        a[0] = value
        print(*a, sep=" ")


n = int(input())
a = [int(token) for token in input().split()]
e = a.pop()
a.append(a[-1])
last_insertion_sort(a, e)

Insertion Sort 2

In [ ]:
def insertionSort(arr):
    for i in range(1, len(arr)):
        temp = arr[i]
        j = i
        while j > 0 and temp < arr[j-1]:
            arr[j] = arr[j-1]
            j -= 1
        arr[j] = temp
        print (' '.join(str(j) for j in arr))

m = input()
arr = [int(i) for i in (input().strip().split())]
insertionSort(arr)